# Generated by Django 4.2.15 on 2025-03-05 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_name', models.CharField(max_length=100)),
                ('standard_quantity', models.IntegerField(default=1)),
                ('replacement_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_checked', models.IntegerField()),
                ('quantity_returned', models.IntegerField(blank=True, null=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accessory')),
            ],
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_description', models.TextField()),
                ('damage_date', models.DateField()),
                ('damage_status', models.CharField(choices=[('reported', 'Reported'), ('confirmed', 'Confirmed'), ('repaired', 'Repaired'), ('charged', 'Charged')], default='reported', max_length=20)),
                ('quantity_damaged', models.IntegerField()),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_status', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accessorychecklist')),
            ],
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('under_maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('condition_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('tent', 'Tent'), ('table', 'Table'), ('chair', 'Chair'), ('canopy', 'Canopy'), ('sleeping_bag', 'Sleeping Bag'), ('cooking_set', 'Cooking Set')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('rental_price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('replacement_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RentalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fines', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RentalItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('rented_price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rentalitem')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rentaltransaction')),
            ],
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rentalitemtype'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('payment_type', models.CharField(choices=[('deposit', 'Deposit'), ('rental_fee', 'Rental Fee'), ('damage_fine', 'Damage Fine'), ('other', 'Other')], max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('damage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.damagereport')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rentaltransaction')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine'), ('repair', 'Repair'), ('replacement', 'Replacement'), ('cleaning', 'Cleaning')], max_length=20)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('technician', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in_progress', 'In Progress')], default='pending', max_length=20)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.accessory')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rentalitem')),
            ],
        ),
        migrations.AddField(
            model_name='damagereport',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.maintenancerecord'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessorychecklist',
            name='rental_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rentalitemdetail'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rentalitemtype'),
        ),
    ]
