# Generated by Django 4.2.15 on 2025-04-24 15:51

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accessory_created_at_accessory_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.rental_item_storage),
        ),
    ]
