# Generated by Django 4.2.15 on 2025-04-29 17:12

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rentalitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('replacement_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='rentalitemdetail',
            name='item',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.payment_slip_storage),
        ),
        migrations.AlterField(
            model_name='rentalitemdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rentaltransaction',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='RentalSetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rented_price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itemset')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rentaltransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rentalitemdetail',
            name='set_rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='core.rentalsetdetail'),
        ),
        migrations.AddField(
            model_name='rentaltransaction',
            name='sets',
            field=models.ManyToManyField(through='core.RentalSetDetail', to='core.itemset'),
        ),
        migrations.CreateModel(
            name='ItemSetComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itemset')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rentalitemtype')),
            ],
            options={
                'unique_together': {('item_set', 'item_type')},
            },
        ),
    ]
