# Generated by Django 4.2.15 on 2025-04-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_itemset_remove_rentalitemdetail_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitemtype',
            name='type_name',
            field=models.CharField(choices=[('tent', 'Tent'), ('table', 'Table'), ('chair', 'Chair'), ('fan', 'Fan'), ('tablecloth', 'Tablecloth')], max_length=50),
        ),
    ]
