# Generated by Django 4.2.15 on 2025-06-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_accessorychecklist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaltransaction',
            name='event_location_notes',
            field=models.TextField(blank=True, help_text='Address or notes about the event location.', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('credit_card', 'Credit Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('under_maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentaltransaction',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
